In [3]:
import pandas as pd
import numpy as np

In [14]:
df_people_analytics = pd.read_csv('../data/projeto_07_people_analytics.csv')

In [23]:
df_people_analytics.head()

,funcionario_id,departamento,cargo,idade,sexo,tempo_empresa_meses,salario_mensal,satisfacao_trabalho,satisfacao_ambiente,equilibrio_vida_trabalho,promovido_ultimos_2anos,horas_extras_mes,num_projetos,avaliacao_desempenho,saiu_da_empresa,data_admissao,data_saida
0,FUN-00001,RH,Coordenador,43,M,50,14397.29,3.0,4,5,1,14,6,2.1,1,2020-10-23,2024-12-01
1,FUN-00002,Suporte,Júnior,35,F,1,2623.53,4.0,5,3,0,5,6,2.7,0,2024-11-01,NaN
2,FUN-00003,Operações,Júnior,29,F,22,3441.92,4.0,3,1,0,2,4,3.9,1,2023-02-10,2024-12-01
3,FUN-00004,Produto,Sênior,29,M,32,13489.71,2.0,2,4,1,4,2,3.5,0,2022-04-16,NaN
4,FUN-00005,Suporte,Pleno,37,M,46,8023.80,2.0,4,3,0,0,1,3.4,1,2021-02-20,2024-12-01

### Existe gap salarial de gênero? Compare salários de homens e mulheres no mesmo cargo e departamento. Quantifique a diferença.

In [ ]:
## Posso começar vendo a média salarial de homens por cargo e departamento, adicionando na mesma tabela a média das mulheres e fazendo a diferença dos dois. Depois estudar a diferença das médias, talvez um gráfico de dispersão me ajude e enxergar

## Os dados estão prontos pra serem usados?
## Departamento, Cargo, Sexo, Salario

print(df_people_analytics[["cargo", "departamento", "sexo", "salario_mensal"]].notnull().sum(), "\n")
# Não existem valores nulos

print("Departamentos:", list(df_people_analytics['departamento'].unique()))
print("Cargos:", list(df_people_analytics['cargo'].unique()))
## Essas são as categorias dos dados

print("Duplicatas de funcionario:", df_people_analytics["funcionario_id"].duplicated().sum())
print("\n",df_people_analytics.dtypes)

df_people_analytics.describe()

df_people_analytics.mean(axis=1)

cargo             1200
departamento      1200
sexo              1200
salario_mensal    1200
dtype: int64

Departamentos: ['RH', 'Suporte', 'Operações', 'Produto', 'Financeiro', 'Vendas', 'Engenharia', 'Marketing']
Cargos: ['Coordenador', 'Júnior', 'Sênior', 'Pleno', 'Gerente']
Duplicatas de funcionario: 0

 funcionario_id                  str
departamento                    str
cargo                           str
idade                         int64
sexo                            str
tempo_empresa_meses           int64
salario_mensal              float64
satisfacao_trabalho         float64
satisfacao_ambiente           int64
equilibrio_vida_trabalho      int64
promovido_ultimos_2anos       int64
horas_extras_mes              int64
num_projetos                  int64
avaliacao_desempenho        float64
saiu_da_empresa               int64
data_admissao                   str
data_saida                      str
dtype: object

,idade,tempo_empresa_meses,salario_mensal,satisfacao_trabalho,satisfacao_ambiente,equilibrio_vida_trabalho,promovido_ultimos_2anos,horas_extras_mes,num_projetos,avaliacao_desempenho,saiu_da_empresa
count,1200.000000,1200.000000,1200.000000,1155.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1171.000000,1200.000000
mean,32.585000,36.029167,8152.508517,2.740260,2.586667,2.550000,0.252500,8.231667,4.129167,3.484543,0.248333
std,6.546003,22.925669,4469.911392,1.116319,1.124815,1.117381,0.434628,5.637181,1.969530,0.797459,0.432226
min,22.000000,1.000000,2101.610000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,28.000000,18.000000,4400.552500,2.000000,2.000000,2.000000,0.000000,4.000000,2.000000,2.900000,0.000000
50%,32.000000,35.000000,7087.290000,3.000000,3.000000,3.000000,0.000000,8.000000,4.000000,3.500000,0.000000
75%,37.000000,52.250000,10703.650000,4.000000,3.000000,3.000000,1.000000,12.000000,6.000000,4.100000,0.000000
max,55.000000,117.000000,27290.830000,5.000000,5.000000,5.000000,1.000000,28.000000,7.000000,5.000000,1.000000